import type {
  BuildingDefinition,
  BuildingType,
  UpgradeLevel,
} from "../solver/types";

export type BuildingId = (typeof BUILDING_TABLE)[number]["id"];

/**
 * The catalogue's three UI groups. The game itself files reactors and direct
 * producers under one `heat_producer` category and the sidebar still shows
 * them on one tab, so the split the solver needs is mapped back here rather
 * than pushed into the UI.
 */
export type BuildingCategory = "cooler" | "generator" | "heat_producer";

export function buildingCategory(type: BuildingType): BuildingCategory {
  return type === "reactor" || type === "direct_producer"
    ? "heat_producer"
    : type;
}

/**
 * The number an upgrade tier is sized by, for callers that do not know the
 * role -- the sidebar's tier list, mostly. Code that does know should read the
 * specific field, which says what the number means.
 */
export function levelValue(level: UpgradeLevel): number {
  return "cooling" in level ? level.cooling : level.heat;
}

/**
 * The upgrade index a placed building is standing at, recovered from the value
 * it was placed at.
 *
 * The inverse of `placementBaseValue`, and the same trick `effectiveAtValue`
 * plays: a placement records a value rather than a level, and a building's tier
 * values strictly increase, so the value identifies the tier exactly for
 * anything the app produced. A value the catalogue does not author -- a
 * hand-edited save -- resolves to the top tier, matching what
 * `effectiveAtValue` would rate it at rather than disagreeing with it.
 *
 * `levels` is read through `readonly UpgradeLevel[]` because
 * `BuildingDefinition` is a four-variant union: `def.levels` is a union of four
 * array types, and calling an array method on that has no single compatible
 * signature. Every variant's element is a `UpgradeLevel`, which is all
 * `levelValue` needs.
 */
export function levelIndexForValue(
  def: BuildingDefinition,
  baseValue: number,
): number {
  const levels: readonly UpgradeLevel[] = def.levels;
  const index = levels.findIndex((level) => levelValue(level) === baseValue);
  return index >= 0 ? index : levels.length - 1;
}

/**
 * The game's authored ScriptableObject values from `Assets/3.Data/Buildings`
 * (`CoolingPerSec` / `HeatPerSec` / `HeatPerTick`, plus `EnergyPerTick` and
 * `WasteHeatPerTick` for generators and the wind turbine) -- not the
 * 3-significant-figure numbers the game's UI displays, and not the extractor's
 * rounded JSON extract. Where they differ the authored value is the
 * real one: cooler2 tier 3 is 18662, not 1.86e4.
 *
 * The table below is generated -- an external extraction script (not in this
 repo) emits it from the game's own files. Don't hand-edit it; everything
 * outside the table is hand-owned and survives regeneration.
 */
// Generated by the roster extraction script -- edit the extractor, not this table.
const BUILDING_TABLE = [
  {
    id: "cooler1",
    type: "cooler",
    name: "Heat Sink #1",
    price: 10,
    displayIndex: 1,
    levels: [
      { cooling: 8 },
      { cooling: 14.4 },
      { cooling: 25.9 },
      { cooling: 46.7 },
      { cooling: 84 },
      { cooling: 151 },
    ],
  },
  {
    id: "cooler2",
    type: "cooler",
    name: "Heat Sink #2",
    price: 40500,
    displayIndex: 2,
    levels: [
      { cooling: 3200 },
      { cooling: 5760 },
      { cooling: 10368 },
      { cooling: 18662 },
      { cooling: 33592 },
      { cooling: 60466 },
    ],
  },
  {
    id: "cooler3",
    type: "cooler",
    name: "Heat Sink #3",
    price: 236000000,
    displayIndex: 3,
    levels: [
      { cooling: 1640000 },
      { cooling: 2950000 },
      { cooling: 5310000 },
      { cooling: 9560000 },
      { cooling: 17200000 },
      { cooling: 31000000 },
    ],
  },
  {
    id: "cooler4",
    type: "cooler",
    name: "Heat Sink #4",
    price: 1380000000000,
    displayIndex: 4,
    levels: [
      { cooling: 1510000000 },
      { cooling: 2720000000 },
      { cooling: 4890000000 },
      { cooling: 8810000000 },
      { cooling: 15900000000 },
      { cooling: 28500000000 },
      { cooling: 51400000000 },
      { cooling: 92400000000 },
    ],
  },
  {
    id: "cooler5",
    type: "cooler",
    name: "Heat Sink #5",
    price: 1.45e17,
    displayIndex: 5,
    levels: [
      { cooling: 4120000000000 },
      { cooling: 7420000000000 },
      { cooling: 13400000000000 },
      { cooling: 24000000000000 },
      { cooling: 43300000000000 },
      { cooling: 77900000000000 },
      { cooling: 140000000000000 },
      { cooling: 252000000000000 },
      { cooling: 453600000000000 },
    ],
  },
  {
    id: "cooler6",
    type: "cooler",
    name: "Heat Sink #6",
    price: 1.52e22,
    displayIndex: 6,
    levels: [
      { cooling: 1.69e16 },
      { cooling: 3.04e16 },
      { cooling: 5.47e16 },
      { cooling: 9.85e16 },
      { cooling: 1.77e17 },
      { cooling: 3.19e17 },
      { cooling: 5.74e17 },
      { cooling: 1.03e18 },
      { cooling: 1.86e18 },
      { cooling: 3.35e18 },
      { cooling: 6.03e18 },
    ],
  },
  {
    id: "cooler7",
    type: "cooler",
    name: "Heat Sink #7",
    price: 1.59e27,
    displayIndex: 7,
    levels: [
      { cooling: 6.92e19 },
      { cooling: 1.25e20 },
      { cooling: 2.24e20 },
      { cooling: 4.03e20 },
      { cooling: 7.26e20 },
      { cooling: 1.31e21 },
      { cooling: 2.35e21 },
    ],
  },
  {
    id: "generator",
    type: "generator",
    name: "Generator #1",
    price: 125,
    displayIndex: 1,
    levels: [
      { heat: 80, energy: 60, waste: 20 },
      { heat: 160, energy: 120, waste: 40 },
      { heat: 320, energy: 240, waste: 80 },
      { heat: 640, energy: 480, waste: 160 },
      { heat: 1280, energy: 960, waste: 320 },
      { heat: 2560, energy: 1920, waste: 640 },
      { heat: 5120, energy: 3840, waste: 1280 },
    ],
  },
  {
    id: "generator2",
    type: "generator",
    name: "Generator #2",
    price: 729000,
    displayIndex: 2,
    levels: [
      { heat: 40960, energy: 30720, waste: 10240 },
      { heat: 81920, energy: 61440, waste: 20480 },
      { heat: 163840, energy: 122880, waste: 40960 },
      { heat: 327680, energy: 245760, waste: 81920 },
      { heat: 655360, energy: 491520, waste: 163840 },
      { heat: 1310000, energy: 983040, waste: 326960 },
    ],
  },
  {
    id: "generator3",
    type: "generator",
    name: "Generator #3",
    price: 4250000000,
    displayIndex: 3,
    levels: [
      { heat: 31500000, energy: 23600000, waste: 7900000 },
      { heat: 62900000, energy: 47200000, waste: 15700000 },
      { heat: 126000000, energy: 94400000, waste: 31600000 },
      { heat: 252000000, energy: 189000000, waste: 63000000 },
      { heat: 503000000, energy: 377000000, waste: 126000000 },
      { heat: 1010000000, energy: 755000000, waste: 255000000 },
      { heat: 2010000000, energy: 1510000000, waste: 500000000 },
      { heat: 4030000000, energy: 3020000000, waste: 1010000000 },
    ],
  },
  {
    id: "generator4",
    type: "generator",
    name: "Generator #4",
    price: 446000000000000,
    displayIndex: 4,
    levels: [
      { heat: 85900000000, energy: 64400000000, waste: 21500000000 },
      { heat: 172000000000, energy: 129000000000, waste: 43000000000 },
      { heat: 344000000000, energy: 258000000000, waste: 86000000000 },
      { heat: 687000000000, energy: 515000000000, waste: 172000000000 },
      { heat: 1370000000000, energy: 1030000000000, waste: 340000000000 },
      { heat: 2750000000000, energy: 2060000000000, waste: 690000000000 },
    ],
  },
  {
    id: "generator5",
    type: "generator",
    name: "Generator #5",
    price: 2.6e18,
    displayIndex: 5,
    levels: [
      { heat: 66000000000000, energy: 49500000000000, waste: 16500000000000 },
      { heat: 132000000000000, energy: 99000000000000, waste: 33000000000000 },
      { heat: 264000000000000, energy: 198000000000000, waste: 66000000000000 },
      {
        heat: 528000000000000,
        energy: 396000000000000,
        waste: 132000000000000,
      },
      {
        heat: 1060000000000000,
        energy: 792000000000000,
        waste: 268000000000000,
      },
      {
        heat: 2110000000000000,
        energy: 1580000000000000,
        waste: 530000000000000,
      },
      {
        heat: 4220000000000000,
        energy: 3170000000000000,
        waste: 1050000000000000,
      },
      {
        heat: 8440000000000000,
        energy: 6330000000000000,
        waste: 2110000000000000,
      },
      { heat: 1.69e16, energy: 1.27e16, waste: 4200000000000000 },
    ],
  },
  {
    id: "generator6",
    type: "generator",
    name: "Generator #6",
    price: 2.73e23,
    displayIndex: 6,
    levels: [
      { heat: 2.7e17, energy: 2.03e17, waste: 6.7e16 },
      { heat: 5.4e17, energy: 4.05e17, waste: 1.35e17 },
      { heat: 1.08e18, energy: 8.11e17, waste: 2.69e17 },
      { heat: 2.16e18, energy: 1.62e18, waste: 5.4e17 },
      { heat: 4.32e18, energy: 3.24e18, waste: 1.08e18 },
      { heat: 8.65e18, energy: 6.49e18, waste: 2.16e18 },
      { heat: 1.73e19, energy: 1.3e19, waste: 4.3e18 },
      { heat: 3.46e19, energy: 2.59e19, waste: 8.7e18 },
      { heat: 6.92e19, energy: 5.19e19, waste: 1.73e19 },
    ],
  },
  {
    id: "generator7",
    type: "generator",
    name: "Generator #7",
    price: 2.87e28,
    displayIndex: 7,
    levels: [
      { heat: 1.11e21, energy: 8.3e20, waste: 2.8e20 },
      { heat: 2.21e21, energy: 1.66e21, waste: 5.5e20 },
      { heat: 4.43e21, energy: 3.32e21, waste: 1.11e21 },
      { heat: 8.85e21, energy: 6.64e21, waste: 2.21e21 },
      { heat: 1.77e22, energy: 1.33e22, waste: 4.4e21 },
    ],
  },
  {
    id: "wind_turbine",
    type: "direct_producer",
    name: "Wind Turbine",
    price: 2,
    displayIndex: 0,
    levels: [
      { heat: 1.25, energy: 1, waste: 0.25 },
      { heat: 2.5, energy: 2, waste: 0.5 },
      { heat: 3.75, energy: 3, waste: 0.75 },
      { heat: 6.25, energy: 5, waste: 1.25 },
      { heat: 8.75, energy: 7, waste: 1.75 },
    ],
  },
  {
    id: "solar_panel",
    type: "reactor",
    name: "Solar Panel",
    price: 400,
    displayIndex: 0,
    levels: [
      { heat: 20 },
      { heat: 25 },
      { heat: 31 },
      { heat: 39 },
      { heat: 49 },
      { heat: 61 },
    ],
  },
  {
    id: "coal_plant",
    type: "reactor",
    name: "Coal Plant",
    price: 7500,
    displayIndex: 0,
    levels: [
      { heat: 160 },
      { heat: 200 },
      { heat: 250 },
      { heat: 313 },
      { heat: 391 },
      { heat: 488 },
    ],
  },
  {
    id: "hydro_plant",
    type: "reactor",
    name: "Hydro Plant",
    price: 162000,
    displayIndex: 0,
    levels: [
      { heat: 1280 },
      { heat: 1600 },
      { heat: 2000 },
      { heat: 2500 },
      { heat: 3125 },
      { heat: 3906 },
    ],
  },
  {
    id: "gas_plant",
    type: "reactor",
    name: "Gas Plant",
    price: 2920000,
    displayIndex: 0,
    levels: [
      { heat: 10240 },
      { heat: 12800 },
      { heat: 16000 },
      { heat: 20000 },
      { heat: 25000 },
      { heat: 31250 },
    ],
  },
  {
    id: "heliothermal_plant",
    type: "reactor",
    name: "Heliothermal Plant",
    price: 52500000,
    displayIndex: 0,
    levels: [
      { heat: 81920 },
      { heat: 102400 },
      { heat: 128000 },
      { heat: 160000 },
      { heat: 200000 },
      { heat: 250000 },
    ],
  },
  {
    id: "geothermal_plant",
    type: "reactor",
    name: "Geothermal Plant",
    price: 945000000,
    displayIndex: 0,
    levels: [
      { heat: 655000 },
      { heat: 819000 },
      { heat: 1020000 },
      { heat: 1280000 },
      { heat: 1600000 },
      { heat: 2000000 },
    ],
  },
  {
    id: "biomass_plant",
    type: "reactor",
    name: "Biomass Plant",
    price: 17000000000,
    displayIndex: 0,
    levels: [
      { heat: 5240000 },
      { heat: 6550000 },
      { heat: 8190000 },
      { heat: 10200000 },
      { heat: 12800000 },
      { heat: 16000000 },
    ],
  },
  {
    id: "nuclear_reactor",
    type: "reactor",
    name: "Nuclear Reactor",
    price: 306000000000,
    displayIndex: 0,
    levels: [
      { heat: 41900000 },
      { heat: 52400000 },
      { heat: 65500000 },
      { heat: 81900000 },
      { heat: 102000000 },
      { heat: 128000000 },
    ],
  },
  {
    id: "fusion_reactor",
    type: "reactor",
    name: "Fusion Reactor",
    price: 5510000000000,
    displayIndex: 0,
    levels: [
      { heat: 336000000 },
      { heat: 419000000 },
      { heat: 524000000 },
      { heat: 655000000 },
      { heat: 819000000 },
      { heat: 1020000000 },
    ],
  },
  {
    id: "arc_reactor",
    type: "reactor",
    name: "Arc Reactor",
    price: 99200000000000,
    displayIndex: 0,
    levels: [
      { heat: 2680000000 },
      { heat: 3360000000 },
      { heat: 4190000000 },
      { heat: 5240000000 },
      { heat: 6550000000 },
      { heat: 8190000000 },
    ],
  },
  {
    id: "antimatter_plant",
    type: "reactor",
    name: "Antimatter Plant",
    price: 1790000000000000,
    displayIndex: 0,
    levels: [
      { heat: 21500000000 },
      { heat: 26800000000 },
      { heat: 33600000000 },
      { heat: 41900000000 },
      { heat: 52400000000 },
      { heat: 65500000000 },
    ],
  },
  {
    id: "quantum_reactor",
    type: "reactor",
    name: "Quantum Reactor",
    price: 3.21e16,
    displayIndex: 0,
    levels: [
      { heat: 172000000000 },
      { heat: 215000000000 },
      { heat: 268000000000 },
      { heat: 336000000000 },
      { heat: 419000000000 },
      { heat: 524000000000 },
    ],
  },
  {
    id: "gravitron_plant",
    type: "reactor",
    name: "Gravitron Plant",
    price: 5.78e17,
    displayIndex: 0,
    levels: [
      { heat: 1370000000000 },
      { heat: 1720000000000 },
      { heat: 2150000000000 },
      { heat: 2680000000000 },
      { heat: 3360000000000 },
      { heat: 4190000000000 },
    ],
  },
  {
    id: "black_hole_reactor",
    type: "reactor",
    name: "Black Hole Reactor",
    price: 1.04e19,
    displayIndex: 0,
    levels: [
      { heat: 11000000000000 },
      { heat: 13700000000000 },
      { heat: 17200000000000 },
      { heat: 21500000000000 },
      { heat: 26800000000000 },
      { heat: 33600000000000 },
    ],
  },
  {
    id: "hyper_space_core",
    type: "reactor",
    name: "HyperSpace Core",
    price: 1.87e20,
    displayIndex: 0,
    levels: [
      { heat: 88000000000000 },
      { heat: 110000000000000 },
      { heat: 137000000000000 },
      { heat: 172000000000000 },
      { heat: 215000000000000 },
      { heat: 268000000000000 },
    ],
  },
  {
    id: "zero_point_reactor",
    type: "reactor",
    name: "Zero-Point Reactor",
    price: 3.37e21,
    displayIndex: 0,
    levels: [
      { heat: 704000000000000 },
      { heat: 880000000000000 },
      { heat: 1100000000000000 },
      { heat: 1370000000000000 },
      { heat: 1720000000000000 },
      { heat: 2150000000000000 },
    ],
  },
  {
    id: "divine_reactor",
    type: "reactor",
    name: "Divine Reactor",
    price: 6.07e22,
    displayIndex: 0,
    levels: [
      { heat: 5630000000000000 },
      { heat: 7040000000000000 },
      { heat: 8800000000000000 },
      { heat: 1.1e16 },
      { heat: 1.37e16 },
      { heat: 1.72e16 },
    ],
  },
  {
    id: "chaos_core",
    type: "reactor",
    name: "Chaos Core",
    price: 1.09e24,
    displayIndex: 0,
    levels: [
      { heat: 4.5e16 },
      { heat: 5.63e16 },
      { heat: 7.04e16 },
      { heat: 8.8e16 },
      { heat: 1.1e17 },
      { heat: 1.37e17 },
    ],
  },
  {
    id: "psionic_tower",
    type: "reactor",
    name: "Psionic Tower",
    price: 1.97e25,
    displayIndex: 0,
    levels: [
      { heat: 3.6e17 },
      { heat: 4.5e17 },
      { heat: 5.63e17 },
      { heat: 7.04e17 },
      { heat: 8.8e17 },
      { heat: 1.1e18 },
    ],
  },
  {
    id: "sauron_eye",
    type: "reactor",
    name: "The All Seeing Eye",
    price: 3.54e26,
    displayIndex: 0,
    levels: [
      { heat: 2.88e18 },
      { heat: 3.6e18 },
      { heat: 4.5e18 },
      { heat: 5.63e18 },
      { heat: 7.04e18 },
      { heat: 8.8e18 },
    ],
  },
  {
    id: "neuro_grid_reactor",
    type: "reactor",
    name: "NeuroGrid Reactor",
    price: 6.37e27,
    displayIndex: 0,
    levels: [
      { heat: 2.31e19 },
      { heat: 2.88e19 },
      { heat: 3.6e19 },
      { heat: 4.5e19 },
      { heat: 5.63e19 },
      { heat: 7.04e19 },
    ],
  },
  {
    id: "flux_reactor",
    type: "reactor",
    name: "Flux Capacitor Reactor",
    price: 1.15e29,
    displayIndex: 0,
    levels: [
      { heat: 1.84e20 },
      { heat: 2.31e20 },
      { heat: 2.88e20 },
      { heat: 3.6e20 },
      { heat: 4.5e20 },
      { heat: 5.63e20 },
    ],
  },
  {
    id: "doomStar_reactor",
    type: "reactor",
    name: "Doom Star Reactor",
    price: 2.07e30,
    displayIndex: 0,
    levels: [
      { heat: 1.48e21 },
      { heat: 1.84e21 },
      { heat: 2.31e21 },
      { heat: 2.88e21 },
      { heat: 3.6e21 },
      { heat: 4.5e21 },
    ],
  },
] as const satisfies readonly BuildingDefinition[];

/**
 * The catalog.
 *
 * The table above is `as const` so `BuildingId` can be derived from it, but
 * that also makes its element type a union of 38 literal object types. Exporting
 * it through a `readonly BuildingDefinition[]` annotation gives every consumer
 * the uniform union instead, so `find(...)` narrows on `type` rather than on
 * whichever literal shape it happened to land on. Same array, not a copy.
 */
export const BUILDINGS: readonly BuildingDefinition[] = BUILDING_TABLE;

/**
 * The same catalog keyed by id, for the handful of call sites that look a
 * building up rather than iterate.
 *
 * `BUILDINGS` stays the array because its order is the order the sidebar and
 * the HUD palette render in, and because everything that consumes the roster
 * -- `getEffectiveBuildings`, the unlock list, the solver hand-off -- walks it
 * whole. Keying the table itself would have bought a lookup this map already
 * provides, at the cost of that ordering being an implementation detail of
 * object key insertion.
 */
const BUILDING_BY_ID: Readonly<Record<string, BuildingDefinition | undefined>> =
  Object.fromEntries(BUILDINGS.map((b) => [b.id, b]));

/**
 * Every building at its top tier — the roster a headless caller wants unless it
 * is modelling a particular save.
 *
 * The retired Python reference spelled this as a module constant called
 * `UNLOCKED_UPGRADES`, and it meant one checkout's progression; it is a
 * function here because nothing in this package has a progression. The app
 * never calls it: what a *player* has unlocked is the player's, and
 * `configState` is where that lives.
 */
export function allUpgradesUnlocked(
  buildings: readonly BuildingDefinition[] = BUILDINGS,
): Record<string, number> {
  const unlocks: Record<string, number> = {};
  for (const building of buildings) {
    unlocks[building.id] = building.levels.length - 1;
  }
  return unlocks;
}

/**
 * Look a building up by id.
 *
 * Every caller arrives with a plain `string` -- a saved placement, a blueprint
 * byte, the tile the user clicked -- so the record is typed over `string` and
 * returns `undefined` for an id the catalog does not carry. That keeps the
 * miss honest at the call site, which handles it anyway, rather than hiding
 * it behind a cast asserting every string is a `BuildingId`.
 */
export function findBuilding(id: string): BuildingDefinition | undefined {
  return BUILDING_BY_ID[id];
}
