"""
The static building roster and the player's unlocked upgrade tiers.

`BUILDINGS` is the game's full catalogue (every upgrade tier of every
building); `UNLOCKED_UPGRADES` picks the tier the player actually owns.
`data.effective_buildings.get_effective_buildings()` collapses the two into the
flat roster the solver and renderer work with.

Every building is one of the four role classes in `solver.types`, which is what
splits the game's own `heat_producer` category into reactors (heat out, no
power) and direct producers (power and heat, no intake).

The figures are the exact ScriptableObject values from the game's
`Assets/3.Data/Buildings` (`CoolingPerSec` / `HeatPerSec` / `HeatPerTick`, plus
`EnergyPerTick` and `WasteHeatPerTick` for generators and the wind turbine),
not the 3-significant-figure numbers the UI displays. Where the two differ the
authored value is the real one: cooler2 tier 3 is 18662, not 1.86e4.

`BUILDINGS` is generated: an external extraction script (not in this repo)
emits it and its TypeScript peer from the same extracted roster, so the port
and its reference cannot disagree about a number. Don't hand-edit the table.
`UNLOCKED_UPGRADES` below is hand-owned -- it is this checkout's progression,
not game data -- and survives regeneration untouched.

Peer: `lib/data/buildings.ts`.
"""

from typing import Dict, List

from solver.types import (
    BuildingDefinition,
    CoolerDefinition,
    CoolerLevel,
    DirectProducerDefinition,
    DirectProducerLevel,
    GeneratorDefinition,
    GeneratorLevel,
    ReactorDefinition,
    ReactorLevel,
)

# Building catalogue: id, price, and the numbers for each upgrade tier.
# Generated by the roster extraction script -- edit the extractor, not this table.
BUILDINGS: List[BuildingDefinition] = [
    CoolerDefinition(
        id="cooler1",
        name="Heat Sink #1",
        price=10,
        display_index=1,
        levels=[
            CoolerLevel(8), CoolerLevel(14.4), CoolerLevel(25.9), CoolerLevel(46.7),
            CoolerLevel(84), CoolerLevel(151),
        ],
    ),
    CoolerDefinition(
        id="cooler2",
        name="Heat Sink #2",
        price=40500,
        display_index=2,
        levels=[
            CoolerLevel(3200), CoolerLevel(5760), CoolerLevel(10368), CoolerLevel(18662),
            CoolerLevel(33592), CoolerLevel(60466),
        ],
    ),
    CoolerDefinition(
        id="cooler3",
        name="Heat Sink #3",
        price=236000000,
        display_index=3,
        levels=[
            CoolerLevel(1640000), CoolerLevel(2950000), CoolerLevel(5310000),
            CoolerLevel(9560000), CoolerLevel(17200000), CoolerLevel(31000000),
        ],
    ),
    CoolerDefinition(
        id="cooler4",
        name="Heat Sink #4",
        price=1380000000000,
        display_index=4,
        levels=[
            CoolerLevel(1510000000), CoolerLevel(2720000000), CoolerLevel(4890000000),
            CoolerLevel(8810000000), CoolerLevel(15900000000), CoolerLevel(28500000000),
            CoolerLevel(51400000000), CoolerLevel(92400000000),
        ],
    ),
    CoolerDefinition(
        id="cooler5",
        name="Heat Sink #5",
        price=1.45e+17,
        display_index=5,
        levels=[
            CoolerLevel(4120000000000), CoolerLevel(7420000000000), CoolerLevel(13400000000000),
            CoolerLevel(24000000000000), CoolerLevel(43300000000000),
            CoolerLevel(77900000000000), CoolerLevel(140000000000000),
            CoolerLevel(252000000000000), CoolerLevel(453600000000000),
        ],
    ),
    CoolerDefinition(
        id="cooler6",
        name="Heat Sink #6",
        price=1.52e+22,
        display_index=6,
        levels=[
            CoolerLevel(1.69e+16), CoolerLevel(3.04e+16), CoolerLevel(5.47e+16),
            CoolerLevel(9.85e+16), CoolerLevel(1.77e+17), CoolerLevel(3.19e+17),
            CoolerLevel(5.74e+17), CoolerLevel(1.03e+18), CoolerLevel(1.86e+18),
            CoolerLevel(3.35e+18), CoolerLevel(6.03e+18),
        ],
    ),
    CoolerDefinition(
        id="cooler7",
        name="Heat Sink #7",
        price=1.59e+27,
        display_index=7,
        levels=[
            CoolerLevel(6.92e+19), CoolerLevel(1.25e+20), CoolerLevel(2.24e+20),
            CoolerLevel(4.03e+20), CoolerLevel(7.26e+20), CoolerLevel(1.31e+21),
            CoolerLevel(2.35e+21),
        ],
    ),
    GeneratorDefinition(
        id="generator",
        name="Generator #1",
        price=125,
        display_index=1,
        levels=[
            GeneratorLevel(80, 60, 20), GeneratorLevel(160, 120, 40),
            GeneratorLevel(320, 240, 80), GeneratorLevel(640, 480, 160),
            GeneratorLevel(1280, 960, 320), GeneratorLevel(2560, 1920, 640),
            GeneratorLevel(5120, 3840, 1280),
        ],
    ),
    GeneratorDefinition(
        id="generator2",
        name="Generator #2",
        price=729000,
        display_index=2,
        levels=[
            GeneratorLevel(40960, 30720, 10240), GeneratorLevel(81920, 61440, 20480),
            GeneratorLevel(163840, 122880, 40960), GeneratorLevel(327680, 245760, 81920),
            GeneratorLevel(655360, 491520, 163840), GeneratorLevel(1310000, 983040, 326960),
        ],
    ),
    GeneratorDefinition(
        id="generator3",
        name="Generator #3",
        price=4250000000,
        display_index=3,
        levels=[
            GeneratorLevel(31500000, 23600000, 7900000),
            GeneratorLevel(62900000, 47200000, 15700000),
            GeneratorLevel(126000000, 94400000, 31600000),
            GeneratorLevel(252000000, 189000000, 63000000),
            GeneratorLevel(503000000, 377000000, 126000000),
            GeneratorLevel(1010000000, 755000000, 255000000),
            GeneratorLevel(2010000000, 1510000000, 500000000),
            GeneratorLevel(4030000000, 3020000000, 1010000000),
        ],
    ),
    GeneratorDefinition(
        id="generator4",
        name="Generator #4",
        price=446000000000000,
        display_index=4,
        levels=[
            GeneratorLevel(85900000000, 64400000000, 21500000000),
            GeneratorLevel(172000000000, 129000000000, 43000000000),
            GeneratorLevel(344000000000, 258000000000, 86000000000),
            GeneratorLevel(687000000000, 515000000000, 172000000000),
            GeneratorLevel(1370000000000, 1030000000000, 340000000000),
            GeneratorLevel(2750000000000, 2060000000000, 690000000000),
        ],
    ),
    GeneratorDefinition(
        id="generator5",
        name="Generator #5",
        price=2.6e+18,
        display_index=5,
        levels=[
            GeneratorLevel(66000000000000, 49500000000000, 16500000000000),
            GeneratorLevel(132000000000000, 99000000000000, 33000000000000),
            GeneratorLevel(264000000000000, 198000000000000, 66000000000000),
            GeneratorLevel(528000000000000, 396000000000000, 132000000000000),
            GeneratorLevel(1060000000000000, 792000000000000, 268000000000000),
            GeneratorLevel(2110000000000000, 1580000000000000, 530000000000000),
            GeneratorLevel(4220000000000000, 3170000000000000, 1050000000000000),
            GeneratorLevel(8440000000000000, 6330000000000000, 2110000000000000),
            GeneratorLevel(1.69e+16, 1.27e+16, 4200000000000000),
        ],
    ),
    GeneratorDefinition(
        id="generator6",
        name="Generator #6",
        price=2.73e+23,
        display_index=6,
        levels=[
            GeneratorLevel(2.7e+17, 2.03e+17, 6.7e+16),
            GeneratorLevel(5.4e+17, 4.05e+17, 1.35e+17),
            GeneratorLevel(1.08e+18, 8.11e+17, 2.69e+17),
            GeneratorLevel(2.16e+18, 1.62e+18, 5.4e+17),
            GeneratorLevel(4.32e+18, 3.24e+18, 1.08e+18),
            GeneratorLevel(8.65e+18, 6.49e+18, 2.16e+18),
            GeneratorLevel(1.73e+19, 1.3e+19, 4.3e+18),
            GeneratorLevel(3.46e+19, 2.59e+19, 8.7e+18),
            GeneratorLevel(6.92e+19, 5.19e+19, 1.73e+19),
        ],
    ),
    GeneratorDefinition(
        id="generator7",
        name="Generator #7",
        price=2.87e+28,
        display_index=7,
        levels=[
            GeneratorLevel(1.11e+21, 8.3e+20, 2.8e+20),
            GeneratorLevel(2.21e+21, 1.66e+21, 5.5e+20),
            GeneratorLevel(4.43e+21, 3.32e+21, 1.11e+21),
            GeneratorLevel(8.85e+21, 6.64e+21, 2.21e+21),
            GeneratorLevel(1.77e+22, 1.33e+22, 4.4e+21),
        ],
    ),
    DirectProducerDefinition(
        id="wind_turbine",
        name="Wind Turbine",
        price=2,
        display_index=0,
        levels=[
            DirectProducerLevel(1.25, 1, 0.25), DirectProducerLevel(2.5, 2, 0.5),
            DirectProducerLevel(3.75, 3, 0.75), DirectProducerLevel(6.25, 5, 1.25),
            DirectProducerLevel(8.75, 7, 1.75),
        ],
    ),
    ReactorDefinition(
        id="solar_panel",
        name="Solar Panel",
        price=400,
        display_index=0,
        levels=[
            ReactorLevel(20), ReactorLevel(25), ReactorLevel(31), ReactorLevel(39),
            ReactorLevel(49), ReactorLevel(61),
        ],
    ),
    ReactorDefinition(
        id="coal_plant",
        name="Coal Plant",
        price=7500,
        display_index=0,
        levels=[
            ReactorLevel(160), ReactorLevel(200), ReactorLevel(250), ReactorLevel(313),
            ReactorLevel(391), ReactorLevel(488),
        ],
    ),
    ReactorDefinition(
        id="hydro_plant",
        name="Hydro Plant",
        price=162000,
        display_index=0,
        levels=[
            ReactorLevel(1280), ReactorLevel(1600), ReactorLevel(2000), ReactorLevel(2500),
            ReactorLevel(3125), ReactorLevel(3906),
        ],
    ),
    ReactorDefinition(
        id="gas_plant",
        name="Gas Plant",
        price=2920000,
        display_index=0,
        levels=[
            ReactorLevel(10240), ReactorLevel(12800), ReactorLevel(16000), ReactorLevel(20000),
            ReactorLevel(25000), ReactorLevel(31250),
        ],
    ),
    ReactorDefinition(
        id="heliothermal_plant",
        name="Heliothermal Plant",
        price=52500000,
        display_index=0,
        levels=[
            ReactorLevel(81920), ReactorLevel(102400), ReactorLevel(128000),
            ReactorLevel(160000), ReactorLevel(200000), ReactorLevel(250000),
        ],
    ),
    ReactorDefinition(
        id="geothermal_plant",
        name="Geothermal Plant",
        price=945000000,
        display_index=0,
        levels=[
            ReactorLevel(655000), ReactorLevel(819000), ReactorLevel(1020000),
            ReactorLevel(1280000), ReactorLevel(1600000), ReactorLevel(2000000),
        ],
    ),
    ReactorDefinition(
        id="biomass_plant",
        name="Biomass Plant",
        price=17000000000,
        display_index=0,
        levels=[
            ReactorLevel(5240000), ReactorLevel(6550000), ReactorLevel(8190000),
            ReactorLevel(10200000), ReactorLevel(12800000), ReactorLevel(16000000),
        ],
    ),
    ReactorDefinition(
        id="nuclear_reactor",
        name="Nuclear Reactor",
        price=306000000000,
        display_index=0,
        levels=[
            ReactorLevel(41900000), ReactorLevel(52400000), ReactorLevel(65500000),
            ReactorLevel(81900000), ReactorLevel(102000000), ReactorLevel(128000000),
        ],
    ),
    ReactorDefinition(
        id="fusion_reactor",
        name="Fusion Reactor",
        price=5510000000000,
        display_index=0,
        levels=[
            ReactorLevel(336000000), ReactorLevel(419000000), ReactorLevel(524000000),
            ReactorLevel(655000000), ReactorLevel(819000000), ReactorLevel(1020000000),
        ],
    ),
    ReactorDefinition(
        id="arc_reactor",
        name="Arc Reactor",
        price=99200000000000,
        display_index=0,
        levels=[
            ReactorLevel(2680000000), ReactorLevel(3360000000), ReactorLevel(4190000000),
            ReactorLevel(5240000000), ReactorLevel(6550000000), ReactorLevel(8190000000),
        ],
    ),
    ReactorDefinition(
        id="antimatter_plant",
        name="Antimatter Plant",
        price=1790000000000000,
        display_index=0,
        levels=[
            ReactorLevel(21500000000), ReactorLevel(26800000000), ReactorLevel(33600000000),
            ReactorLevel(41900000000), ReactorLevel(52400000000), ReactorLevel(65500000000),
        ],
    ),
    ReactorDefinition(
        id="quantum_reactor",
        name="Quantum Reactor",
        price=3.21e+16,
        display_index=0,
        levels=[
            ReactorLevel(172000000000), ReactorLevel(215000000000), ReactorLevel(268000000000),
            ReactorLevel(336000000000), ReactorLevel(419000000000), ReactorLevel(524000000000),
        ],
    ),
    ReactorDefinition(
        id="gravitron_plant",
        name="Gravitron Plant",
        price=5.78e+17,
        display_index=0,
        levels=[
            ReactorLevel(1370000000000), ReactorLevel(1720000000000),
            ReactorLevel(2150000000000), ReactorLevel(2680000000000),
            ReactorLevel(3360000000000), ReactorLevel(4190000000000),
        ],
    ),
    ReactorDefinition(
        id="black_hole_reactor",
        name="Black Hole Reactor",
        price=1.04e+19,
        display_index=0,
        levels=[
            ReactorLevel(11000000000000), ReactorLevel(13700000000000),
            ReactorLevel(17200000000000), ReactorLevel(21500000000000),
            ReactorLevel(26800000000000), ReactorLevel(33600000000000),
        ],
    ),
    ReactorDefinition(
        id="hyper_space_core",
        name="HyperSpace Core",
        price=1.87e+20,
        display_index=0,
        levels=[
            ReactorLevel(88000000000000), ReactorLevel(110000000000000),
            ReactorLevel(137000000000000), ReactorLevel(172000000000000),
            ReactorLevel(215000000000000), ReactorLevel(268000000000000),
        ],
    ),
    ReactorDefinition(
        id="zero_point_reactor",
        name="Zero-Point Reactor",
        price=3.37e+21,
        display_index=0,
        levels=[
            ReactorLevel(704000000000000), ReactorLevel(880000000000000),
            ReactorLevel(1100000000000000), ReactorLevel(1370000000000000),
            ReactorLevel(1720000000000000), ReactorLevel(2150000000000000),
        ],
    ),
    ReactorDefinition(
        id="divine_reactor",
        name="Divine Reactor",
        price=6.07e+22,
        display_index=0,
        levels=[
            ReactorLevel(5630000000000000), ReactorLevel(7040000000000000),
            ReactorLevel(8800000000000000), ReactorLevel(1.1e+16), ReactorLevel(1.37e+16),
            ReactorLevel(1.72e+16),
        ],
    ),
    ReactorDefinition(
        id="chaos_core",
        name="Chaos Core",
        price=1.09e+24,
        display_index=0,
        levels=[
            ReactorLevel(4.5e+16), ReactorLevel(5.63e+16), ReactorLevel(7.04e+16),
            ReactorLevel(8.8e+16), ReactorLevel(1.1e+17), ReactorLevel(1.37e+17),
        ],
    ),
    ReactorDefinition(
        id="psionic_tower",
        name="Psionic Tower",
        price=1.97e+25,
        display_index=0,
        levels=[
            ReactorLevel(3.6e+17), ReactorLevel(4.5e+17), ReactorLevel(5.63e+17),
            ReactorLevel(7.04e+17), ReactorLevel(8.8e+17), ReactorLevel(1.1e+18),
        ],
    ),
    ReactorDefinition(
        id="sauron_eye",
        name="The All Seeing Eye",
        price=3.54e+26,
        display_index=0,
        levels=[
            ReactorLevel(2.88e+18), ReactorLevel(3.6e+18), ReactorLevel(4.5e+18),
            ReactorLevel(5.63e+18), ReactorLevel(7.04e+18), ReactorLevel(8.8e+18),
        ],
    ),
    ReactorDefinition(
        id="neuro_grid_reactor",
        name="NeuroGrid Reactor",
        price=6.37e+27,
        display_index=0,
        levels=[
            ReactorLevel(2.31e+19), ReactorLevel(2.88e+19), ReactorLevel(3.6e+19),
            ReactorLevel(4.5e+19), ReactorLevel(5.63e+19), ReactorLevel(7.04e+19),
        ],
    ),
    ReactorDefinition(
        id="flux_reactor",
        name="Flux Capacitor Reactor",
        price=1.15e+29,
        display_index=0,
        levels=[
            ReactorLevel(1.84e+20), ReactorLevel(2.31e+20), ReactorLevel(2.88e+20),
            ReactorLevel(3.6e+20), ReactorLevel(4.5e+20), ReactorLevel(5.63e+20),
        ],
    ),
    ReactorDefinition(
        id="doomStar_reactor",
        name="Doom Star Reactor",
        price=2.07e+30,
        display_index=0,
        levels=[
            ReactorLevel(1.48e+21), ReactorLevel(1.84e+21), ReactorLevel(2.31e+21),
            ReactorLevel(2.88e+21), ReactorLevel(3.6e+21), ReactorLevel(4.5e+21),
        ],
    ),
]


# building_id -> index into that building's `levels` list.
# Buildings absent from this map are treated as locked and are filtered out.
# Dynamically unlock every building at its maximum tier index (len(levels) - 1).
UNLOCKED_UPGRADES: Dict[str, int] = {
    b.id: len(b.levels) - 1 for b in BUILDINGS
}
