"""
Pins the portable PRNG (`solver/rng.py`) to the canonical JS mulberry32.

The golden values below were generated by the JS reference implementation
quoted in the module's docstring, run under Node v20, and must match
bit-for-bit: this is what lets a seeded Python solve be replayed by the JS
port of the solver and vice versa. If one of these assertions fails, the
Python implementation has drifted from the JS semantics -- fix the code, do
NOT re-record the values from Python output.
"""

import unittest

from solver.rng import Rng

# seed -> first five outputs of the JS reference (Node v20, exact doubles).
GOLDEN = {
    0: [
        0.26642920868471265,
        0.0003297457005828619,
        0.2232720274478197,
        0.1462021479383111,
        0.46732782293111086,
    ],
    1: [
        0.6270739405881613,
        0.002735721180215478,
        0.5274470399599522,
        0.9810509674716741,
        0.9683778982143849,
    ],
    42: [
        0.6011037519201636,
        0.44829055899754167,
        0.8524657934904099,
        0.6697340414393693,
        0.17481389874592423,
    ],
    123456789: [
        0.2577907438389957,
        0.9707721115555614,
        0.7853280142880976,
        0.20616457983851433,
        0.30307188746519387,
    ],
    4294967295: [
        0.8964226141106337,
        0.189478256739676,
        0.7156526781618595,
        0.9440599093213677,
        0.8452364315744489,
    ],
}


class TestRngMatchesJsReference(unittest.TestCase):
    def test_streams_match_the_js_reference_bit_for_bit(self):
        for seed, expected in GOLDEN.items():
            rng = Rng(seed)
            got = [rng.random() for _ in range(len(expected))]
            self.assertEqual(got, expected, f"stream diverged for seed {seed}")

    def test_seed_wraps_to_32_bits(self):
        # JS coerces the seed with `a |= 0`; only the low 32 bits matter.
        wide, narrow = Rng(2**32 + 7), Rng(7)
        self.assertEqual(
            [wide.random() for _ in range(10)],
            [narrow.random() for _ in range(10)],
        )

    def test_outputs_stay_in_unit_interval(self):
        rng = Rng(20260818)
        for _ in range(10_000):
            value = rng.random()
            self.assertGreaterEqual(value, 0.0)
            self.assertLess(value, 1.0)


class TestDrawHelpers(unittest.TestCase):
    def test_choice_is_deterministic_and_in_range(self):
        items = list(range(17))
        picks = [Rng(9).choice(items) for _ in range(1)]
        self.assertEqual(picks, [Rng(9).choice(items)])
        rng = Rng(1234)
        for _ in range(1_000):
            self.assertIn(rng.choice(items), items)

    def test_shuffle_is_a_deterministic_permutation(self):
        a, b = list(range(20)), list(range(20))
        Rng(77).shuffle(a)
        Rng(77).shuffle(b)
        self.assertEqual(a, b)
        self.assertEqual(sorted(a), list(range(20)))
        self.assertNotEqual(a, list(range(20)), "shuffle left the list untouched")


if __name__ == "__main__":
    unittest.main()
